### PR TITLE
Turkish translations added to homepage and messages

### PR DESCRIPTION
**Pull request by muratbsts**

### CODE REVIEW

**Comment by MadLittleMods** [comment]
Thanks @muratbsts 😀

**Comment by muratbsts** [comment]
Hi, @MadLittleMods you're welcome. How to change the language of gitter.im website for an overview?

**Comment by MadLittleMods** [comment]
@muratbsts This won't be available until we update the dependency in the `webapp` and push out a release.

I assume it picks up your locale from your OS/browser preferences.

**Comment by muratbsts** [comment]
Thanks @MadLittleMods I understand.

**Pull request merged**
