### PR TITLE
lt.js - Lithuanian

### PR DESCRIPTION
**Pull request by mataslt**
I have created another translation for my native language, Lithuanian. If you have any questions or enquiries please don't hesitate to message me.

Matas

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@mataslt Can you get another native Lithuanian speaker to review this?

**Comment by mataslt** [comment]
Yes certainly, I can get my friend which is also a Lithuanian native, to review this. I will send you his email address tomorrow and you can contact him for your confirmation about his native language.

Thanks
Matas

**Comment by MadLittleMods** [comment]
@mataslt Just ping them here via mention.

**Comment by mataslt** [comment]
Yes okay, his username is @swarcaslt he will review it in 5 to 10 minutes.
Thanks.

**Comment by swarcaslt** [comment]
Hello, 
I have reviewed the work done by @mataslt. And I can confirm that the translations are all done corectly. 
Best Regards.

**Comment by suprememoocow** [comment]
And Google Translate concurs too. Thanks @mataslt, @swarcaslt

**Pull request merged**
