### PR TITLE
Fix typos and grammar errors in Ukrainian translation

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by MadLittleMods** [comment]
Google translate seems to check out on this.

**Comment by webknjaz** [comment]
Well, I'm a native speaker. Trust me :)

Let's ask original translation author @dimonzz (#24) approve my changes.

**Comment by dimonzz** [comment]
@MadLittleMods sounds good. It can be merged I think.
@webknjaz thanks for corrections.

**Comment by MadLittleMods** [comment]
@webknjaz Thanks for the contribution!

**Pull request merged**
