### PR TITLE
Update nl.js

### PR DESCRIPTION
**Pull request by bobmulder**
Please let me know if I did it right. Is this integrated already?

### CODE REVIEW

**Comment by cutandpastey** [comment]
@bobmulder Thanks for the translations, unfortunately there is a merge conflict. If you can get this sorted I would be happy to merge this ASAP. Thanks!

**Comment by bobmulder** [comment]
I will when I got time ;)

**Comment by MadLittleMods** [comment]
@bobmulder Just checking in, what's your plan with this?

**Comment by bobmulder** [comment]
No plans at all. If you need dutch translation I could create a new PR to avoid the merge conflict...

**Comment by MadLittleMods** [comment]
If you see any problems with the current dutch translation, we welcome a PR :)

**Pull request closed without merging**
