### PR TITLE
Add French translation for homepage (incomplete)

### PR DESCRIPTION
**Pull request by yaningo**
- Lines fully translated:
    * 2 --> 18
    * 20 --> 33
    * 39 --> 41
    * 45 --> 52
    * 63

- Lines left to translate:
    * 19
    * 35 --> 37
    * 43, 44
    * 53 --> 61
    * 64, 65

- No translation needed for lines:
    * 8 --> 10
    * 32
    * 66 --> 71

### CODE REVIEW

**Comment by LAfricain** [comment]
What about the French translation?
Can I help?

**Comment by MadLittleMods** [comment]
@LAfricain If the translations look good, would appreciate a :+1: confirmation 😀

**Comment by MadLittleMods** [comment]
@yaningo Any interest in reviving this on https://gitlab.com/gitlab-org/gitter/gitter-translations/merge_requests/46 ? (Project moved to GitLab)

**Comment by yaningo** [comment]
> @yaningo Any interest in reviving this on https://gitlab.com/gitlab-org/gitter/gitter-translations/merge_requests/46 ? (Project moved to GitLab)

See you there...

**Pull request closed without merging**
