### PR TITLE
Added Ukrainian translations

### PR DESCRIPTION
**Pull request by dimonzz**
Take a look at subject

### CODE REVIEW

**Comment by denysdovhan** [comment]
Nice work :+1: 
I've left few comments, which, I hope, will make it a little bit better. Can't wait anymore when it will be merged!

@suprememoocow, @MadLittleMods, @mydigitalself, Guys, can anyone finally check it and merge as soon as it can be possible?

**Comment by MadLittleMods** [comment]
What happened with the commit history on this? @denysdovhan made comments on the same commit hash yet some seem fixed and they did not suppress.

**Comment by denysdovhan** [comment]
Commits aren't fixed yet. I've made just a small review. @dimonzz can you fix your commits?

**Comment by dimonzz** [comment]
@denysdovhan thank you for adjustments. I'll implement them ASAP.

**Comment by denysdovhan** [comment]
LGTM! 
It might be merged.

**Comment by MadLittleMods** [comment]
Merging now, Thank you @dimonzz for the PR and @denysdovhan for review!

**Comment by denysdovhan** [comment]
:+1:

**Pull request merged**
